"""GitHub Statistics Engine for EL-STRIX."""

from datetime import UTC, datetime, timedelta
from typing import Any

from logger import logger
from paths import PathManager
from utils.json_helpers import load_json, save_json


class StatisticsEngine:
    """Core engine for processing GitHub data into statistics.

    The Statistics Engine never communicates directly with GitHub APIs.
    It reads JSON data generated by the GitHub Data Engine and acts as the
    single source of truth for every numerical value displayed in the profile.
    """

    def __init__(self) -> None:
        """Initialize the StatisticsEngine and load raw data."""
        self.profile_data: dict[str, Any] = load_json(
            PathManager.GENERATED_JSON_DIR / "profile.json"
        )
        self.repos_data: list[dict[str, Any]] = load_json(
            PathManager.GENERATED_JSON_DIR / "repos.json"
        )
        if not isinstance(self.repos_data, list):
            self.repos_data = []
        self.contrib_data: dict[str, Any] = load_json(
            PathManager.GENERATED_JSON_DIR / "contributions.json"
        )
        self.loc_data: dict[str, Any] = load_json(PathManager.GENERATED_JSON_DIR / "loc_stats.json")
        self.pr_data: list[dict[str, Any]] = load_json(
            PathManager.GENERATED_JSON_DIR / "pull_requests.json"
        )
        if not isinstance(self.pr_data, list):
            self.pr_data = []
        self.releases_data: dict[str, Any] = load_json(
            PathManager.GENERATED_JSON_DIR / "releases.json"
        )
        self.issues_data: list[dict[str, Any]] = load_json(
            PathManager.GENERATED_JSON_DIR / "issues.json"
        )
        if not isinstance(self.issues_data, list):
            self.issues_data = []
        self.stats: dict[str, Any] = {}

    def process_all(self) -> dict[str, Any]:
        """Execute the complete data processing pipeline."""
        logger.info("StatisticsEngine: Processing started.")
        start_time = datetime.now(UTC)

        # 1. Validation
        if not self._validate_data():
            logger.error("StatisticsEngine: Validation failed. Proceeding with available data.")

        # 2. Normalization
        self._normalize_data()

        # 3. Calculation & Aggregation
        self.stats = {
            "profile": self._calculate_profile_stats(),
            "repositories": self._calculate_repo_stats(),
            "stars": self._calculate_star_stats(),
            "forks": self._calculate_fork_stats(),
            "commits": self._calculate_commit_stats(),
            "contributions": self._calculate_contribution_stats(),
            "loc": self._calculate_loc_stats(),
            "languages": self._calculate_language_stats(),
            "activity": self._calculate_repo_activity(),
            "releases": self._calculate_release_stats(),
            "issues": self._calculate_issue_stats(),
            "pull_requests": self._calculate_pr_stats(),
            "featured_projects": self._calculate_featured_projects(),
            "trends": self._calculate_trends(),
            "recent_activity": self._generate_recent_activity(),
            "summary": self._generate_profile_summary(),
        }

        # 4. Output JSON
        self._save_output()

        duration = (datetime.now(UTC) - start_time).total_seconds()
        logger.info(f"StatisticsEngine: Processing completed in {duration:.2f}s.")
        return self.stats

    def _validate_data(self) -> bool:
        """Validate the presence and integrity of raw data."""
        valid = True
        if not self.profile_data:
            logger.warning("Validation Warning: Missing or empty profile.json")
            valid = False
        if not self.repos_data:
            logger.warning("Validation Warning: Missing or empty repos.json")
            valid = False
        if not self.contrib_data:
            logger.warning("Validation Warning: Missing or empty contributions.json")
            valid = False
        return valid

    def _normalize_data(self) -> None:
        """Normalize data structures before processing."""
        for repo in self.repos_data:
            repo["stargazers_count"] = repo.get("stargazers_count", 0)
            repo["forks_count"] = repo.get("forks_count", 0)
            repo["size"] = repo.get("size", 0)

    def _parse_date(self, date_str: str | None) -> datetime | None:
        """Parse ISO 8601 date string to datetime object."""
        if not date_str:
            return None
        try:
            return datetime.fromisoformat(date_str.replace("Z", "+00:00"))
        except ValueError:
            return None

    def _calculate_profile_stats(self) -> dict[str, Any]:
        """Calculate profile-level statistics."""
        created_at_str = self.profile_data.get("created_at")
        created_date = self._parse_date(created_at_str)

        days_since_creation = 0
        account_age_years = 0.0
        if created_date:
            delta = datetime.now(UTC) - created_date
            days_since_creation = delta.days
            account_age_years = round(days_since_creation / 365.25, 2)

        return {
            "total_public_repositories": self.profile_data.get("public_repos", 0),
            "total_followers": self.profile_data.get("followers", 0),
            "total_following": self.profile_data.get("following", 0),
            "profile_creation_date": created_at_str,
            "days_since_account_creation": days_since_creation,
            "account_age_years": account_age_years,
        }

    def _calculate_repo_stats(self) -> dict[str, Any]:
        """Calculate repository-level statistics."""
        # Calculate exactly based on the fully paginated repositories fetched
        public = sum(1 for r in self.repos_data if not r.get("private"))
        private = sum(1 for r in self.repos_data if r.get("private"))
        total = public + private

        archived = sum(1 for r in self.repos_data if r.get("archived"))
        forked = sum(1 for r in self.repos_data if r.get("fork"))
        original = total - forked

        now = datetime.now(UTC)
        active = 0
        for r in self.repos_data:
            updated = self._parse_date(r.get("pushed_at") or r.get("updated_at"))
            if updated and (now - updated).days <= 90:
                active += 1

        return {
            "repository_count": total,
            "public_repository_count": public,
            "private_repository_count": private,
            "archived_repository_count": archived,
            "forked_repository_count": forked,
            "original_repository_count": original,
            "active_repository_count": active,
            "repository_growth": total,
        }

    def _calculate_star_stats(self) -> dict[str, Any]:
        """Calculate star-level statistics."""
        if not self.repos_data:
            return {"total_stars": 0, "average_stars": 0.0}

        stars = [r.get("stargazers_count", 0) for r in self.repos_data if not r.get("fork")]
        total = sum(stars)
        avg = round(total / len(stars), 2) if stars else 0.0

        repo_stars = {
            r.get("name", "unknown"): r.get("stargazers_count", 0)
            for r in self.repos_data
            if not r.get("fork")
        }
        sorted_repos = sorted(repo_stars.items(), key=lambda x: x[1], reverse=True)

        return {
            "total_stars": total,
            "average_stars": avg,
            "most_starred_repository": sorted_repos[0][0] if sorted_repos else None,
            "least_starred_repository": sorted_repos[-1][0] if sorted_repos else None,
            "star_ranking": [{"repository": k, "stars": v} for k, v in sorted_repos],
            "star_distribution": self._bucket_distribution(stars),
        }

    def _bucket_distribution(self, values: list[int]) -> dict[str, int]:
        """Create a generic bucketed distribution."""
        dist = {"0": 0, "1-10": 0, "11-50": 0, "51-100": 0, "100+": 0}
        for v in values:
            if v == 0:
                dist["0"] += 1
            elif v <= 10:
                dist["1-10"] += 1
            elif v <= 50:
                dist["11-50"] += 1
            elif v <= 100:
                dist["51-100"] += 1
            else:
                dist["100+"] += 1
        return dist

    def _calculate_fork_stats(self) -> dict[str, Any]:
        """Calculate fork statistics."""
        if not self.repos_data:
            return {"total_forks": 0}

        forks = [r.get("forks_count", 0) for r in self.repos_data if not r.get("fork")]
        total = sum(forks)
        avg = round(total / len(forks), 2) if forks else 0.0

        repo_forks = {
            r.get("name", "unknown"): r.get("forks_count", 0)
            for r in self.repos_data
            if not r.get("fork")
        }
        sorted_repos = sorted(repo_forks.items(), key=lambda x: x[1], reverse=True)

        return {
            "total_forks": total,
            "average_forks": avg,
            "most_forked_repository": sorted_repos[0][0] if sorted_repos else None,
            "repository_fork_rankings": [{"repository": k, "forks": v} for k, v in sorted_repos],
        }

    def _calculate_commit_stats(self) -> dict[str, Any]:
        """Calculate commit statistics."""
        # Include restrictedContributionsCount (private contributions) to accurately reflect the
        # total shown on the user's GitHub contributions graph.
        total_commits = self.contrib_data.get(
            "totalCommitContributions", 0
        ) + self.contrib_data.get("restrictedContributionsCount", 0)

        calendar = self.contrib_data.get("contributionCalendar", {})
        weeks = calendar.get("weeks", [])

        # Collect unique days with their commit counts
        unique_days: dict[str, int] = {}
        for week in weeks:
            for day in week.get("contributionDays", []):
                d = day.get("date", "")
                if d:
                    unique_days[d] = max(unique_days.get(d, 0), day.get("contributionCount", 0))

        # Determine effective today for GitHub data (aligned with UTC and active commit dates)
        github_today = datetime.now(UTC).date()
        active_dates = [datetime.strptime(d, "%Y-%m-%d").date() for d, c in unique_days.items() if c > 0]
        if active_dates and max(active_dates) > github_today:
            today = max(active_dates)
        else:
            today = github_today

        thirty_days_ago = today - timedelta(days=30)
        today_str = today.strftime("%Y-%m-%d")

        recent_commits = 0
        timeline = []

        curr = thirty_days_ago
        while curr <= today:
            d_str = curr.strftime("%Y-%m-%d")
            count = unique_days.get(d_str, 0)
            recent_commits += count
            timeline.append({"date": d_str, "commits": count})
            curr += timedelta(days=1)

        frequency = round(recent_commits / 30, 2)

        commits_per_repo = {}
        if self.loc_data and isinstance(self.loc_data, dict):
            for repo, data in self.loc_data.items():
                c = data.get("total_commits", 0)
                if c > 0:
                    commits_per_repo[repo] = c

        return {
            "total_commits": total_commits,
            "recent_commits": recent_commits,
            "commit_frequency": frequency,
            "commits_per_repository": commits_per_repo,
            "commit_timeline": timeline,
        }

    def _calculate_contribution_stats(self) -> dict[str, Any]:
        """Calculate generalized contribution stats including streaks."""
        calendar = self.contrib_data.get("contributionCalendar", {})
        weeks = calendar.get("weeks", [])

        # Flatten days, deduplicate by date keeping maximum count
        unique_days: dict[str, int] = {}
        for week in weeks:
            for day in week.get("contributionDays", []):
                d = day.get("date", "")
                if d:
                    unique_days[d] = max(unique_days.get(d, 0), day.get("contributionCount", 0))

        if not unique_days:
            return {
                "total_contributions": 0,
                "max_daily_contributions": 0,
                "current_streak": 0,
                "longest_streak": 0,
                "yearly_contributions": 0,
            }

        # Determine effective today (aligned with GitHub UTC timeline, allowing forward active dates)
        github_today = datetime.now(UTC).date()
        active_dates = [datetime.strptime(d, "%Y-%m-%d").date() for d, c in unique_days.items() if c > 0]
        if active_dates and max(active_dates) > github_today:
            today = max(active_dates)
        else:
            today = github_today

        all_dates = [datetime.strptime(d, "%Y-%m-%d").date() for d in unique_days.keys()]
        start_date = min(all_dates)

        # Build continuous daily contribution mapping from start_date to today
        curr = start_date
        temp_streak = 0
        longest_streak = 0
        max_daily = 0
        daily_counts: dict[str, int] = {}

        while curr <= today:
            d_str = curr.strftime("%Y-%m-%d")
            count = unique_days.get(d_str, 0)
            daily_counts[d_str] = count
            max_daily = max(max_daily, count)

            if count > 0:
                temp_streak += 1
                if temp_streak > longest_streak:
                    longest_streak = temp_streak
            else:
                temp_streak = 0

            curr += timedelta(days=1)

        # Calculate current streak:
        # 1. If today has contributions, streak is active ending today.
        # 2. If today has 0 contributions, but yesterday had contributions, the streak is still active up through yesterday.
        # 3. If both today and yesterday have 0 contributions, streak is 0.
        today_str = today.strftime("%Y-%m-%d")
        yesterday_str = (today - timedelta(days=1)).strftime("%Y-%m-%d")

        today_count = daily_counts.get(today_str, 0)
        yesterday_count = daily_counts.get(yesterday_str, 0)

        current_streak = 0
        if today_count > 0:
            check_date = today
            while True:
                c_str = check_date.strftime("%Y-%m-%d")
                if daily_counts.get(c_str, 0) > 0:
                    current_streak += 1
                    check_date -= timedelta(days=1)
                else:
                    break
        elif yesterday_count > 0:
            check_date = today - timedelta(days=1)
            while True:
                c_str = check_date.strftime("%Y-%m-%d")
                if daily_counts.get(c_str, 0) > 0:
                    current_streak += 1
                    check_date -= timedelta(days=1)
                else:
                    break

        longest_streak = max(longest_streak, current_streak)

        # Total contributions: sum unique days up to today + restricted private contributions
        total_contributions = sum(
            count for d_str, count in unique_days.items()
            if d_str <= today_str
        ) + self.contrib_data.get("restrictedContributionsCount", 0)

        return {
            "total_contributions": total_contributions,
            "max_daily_contributions": max_daily,
            "current_streak": current_streak,
            "longest_streak": longest_streak,
            "yearly_contributions": total_contributions,
        }

    def _calculate_loc_stats(self) -> dict[str, Any]:
        """Calculate lines of code stats based on actual physical file counts."""
        total_lines = 0

        if self.loc_data and isinstance(self.loc_data, dict):
            for repo_name, data in self.loc_data.items():
                total_lines += data.get("total_lines", 0)

        return {
            "total_lines": total_lines,
        }

    def _calculate_language_stats(self) -> dict[str, Any]:
        """Calculate language usage."""
        lang_bytes: dict[str, int] = {}
        for r in self.repos_data:
            if r.get("fork"):
                continue
            lang = r.get("language")
            if lang:
                lang_bytes[lang] = lang_bytes.get(lang, 0) + r.get("size", 0) * 1024

        total_bytes = sum(lang_bytes.values())
        sorted_langs = sorted(lang_bytes.items(), key=lambda x: x[1], reverse=True)

        percentages = {}
        if total_bytes > 0:
            percentages = {k: round((v / total_bytes) * 100, 2) for k, v in sorted_langs}

        return {
            "languages_used": len(lang_bytes),
            "total_bytes": total_bytes,
            "most_used_language": sorted_langs[0][0] if sorted_langs else None,
            "percentage_per_language": percentages,
            "language_ranking": [
                {"language": k, "bytes": v, "percentage": percentages.get(k)}
                for k, v in sorted_langs
            ],
        }

    def _calculate_repo_activity(self) -> dict[str, Any]:
        """Calculate repository activity timing."""
        valid_repos = [
            r
            for r in self.repos_data
            if not r.get("fork") and r.get("created_at") and r.get("pushed_at")
        ]
        if not valid_repos:
            return {}

        sorted_by_recent = sorted(
            valid_repos,
            key=lambda x: self._parse_date(x["pushed_at"]) or datetime.min.replace(tzinfo=UTC),
            reverse=True,
        )
        sorted_by_created = sorted(
            valid_repos,
            key=lambda x: self._parse_date(x["created_at"]) or datetime.min.replace(tzinfo=UTC),
        )

        return {
            "most_recently_updated_repository": sorted_by_recent[0].get("name")
            if sorted_by_recent
            else None,
            "recently_created_repository": sorted_by_created[-1].get("name")
            if sorted_by_created
            else None,
            "oldest_repository": sorted_by_created[0].get("name") if sorted_by_created else None,
            "most_active_repository": None,
            "least_active_repository": None,
        }

    def _calculate_release_stats(self) -> dict[str, Any]:
        total_releases = 0
        latest_release_date = None
        latest_release_name = None
        repo_release_count = {}

        for repo_name, releases in self.releases_data.items():
            count = len(releases)
            if count > 0:
                total_releases += count
                repo_release_count[repo_name] = count

                # Check for latest release
                for release in releases:
                    pub_date = self._parse_date(release.get("publishedAt"))
                    if pub_date:
                        if not latest_release_date or pub_date > latest_release_date:
                            latest_release_date = pub_date
                            latest_release_name = release.get("name") or release.get("tagName")

        return {
            "total_releases": total_releases,
            "latest_release": latest_release_name,
            "release_frequency": 0.0,  # Could be calculated if needed
            "repository_release_count": repo_release_count,
        }

    def _calculate_issue_stats(self) -> dict[str, Any]:
        # Filter to ensure we only count actual issues, not PRs (Search API sometimes mixes them if not careful)
        # We explicitly searched `type:issue`, so they should all be issues.
        total_issues = len(self.issues_data)
        open_issues = 0
        closed_issues = 0
        for issue in self.issues_data:
            state = issue.get("state")
            if state == "open":
                open_issues += 1
            elif state == "closed":
                closed_issues += 1

        # If the search API limit was hit (1000), total might be capped.
        # Fallback to totalIssueContributions from GraphQL if it's larger.
        graphql_total = self.contrib_data.get("totalIssueContributions", 0)
        if graphql_total > total_issues:
            total_issues = graphql_total
            # We can't know the exact open/closed split for the missing ones,
            # but we can scale closed_issues to match the new total if we assume the fetched ones are a representative sample.
            # However, since we sorted by updated_desc, open issues are usually active/recent and fully fetched.
            # We will just pad closed_issues.
            closed_issues = max(0, total_issues - open_issues)

        ratio = round((closed_issues / total_issues) * 100, 2) if total_issues > 0 else 0.0

        return {
            "total_issues": total_issues,
            "open_issues": open_issues,
            "closed_issues": closed_issues,
            "issue_ratio": ratio,
        }

    def _calculate_pr_stats(self) -> dict[str, Any]:
        username = (self.profile_data.get("login") or "").lower()

        # Filter PRs to only those authored by the user
        filtered_prs = []
        for pr in self.pr_data:
            author = (pr.get("user", {}).get("login") or "").lower()
            if author == username:
                filtered_prs.append(pr)

        total = len(filtered_prs)

        open_prs = 0
        merged_prs = 0
        closed_prs = 0

        for pr in filtered_prs:
            state = pr.get("state")
            if state == "open":
                open_prs += 1
            elif state == "closed":
                closed_prs += 1

            if pr.get("merged_at") or pr.get("pull_request", {}).get("merged_at"):
                merged_prs += 1

        closed_prs -= merged_prs

        return {
            "total_pull_requests": total,
            "open_pull_requests": open_prs,
            "closed_pull_requests": max(0, closed_prs),
            "merged_pull_requests": merged_prs,
        }

    def _calculate_featured_projects(self) -> list[dict[str, Any]]:
        """Rank repositories for featuring."""
        from projects import format_featured, select_featured

        selected = select_featured(self.repos_data, max_count=6)
        return format_featured(selected)

    def _calculate_trends(self) -> dict[str, Any]:
        # Repository growth trend
        repos_by_year = {}
        for r in self.repos_data:
            created = self._parse_date(r.get("created_at"))
            if created:
                year = str(created.year)
                repos_by_year[year] = repos_by_year.get(year, 0) + 1

        repo_growth = [{"year": k, "count": v} for k, v in sorted(repos_by_year.items())]

        # Commit trend from calendar
        commit_trend = []
        calendar = self.contrib_data.get("contributionCalendar", {})
        seen_weeks = set()

        today_str = datetime.now(UTC).strftime("%Y-%m-%d")

        for week in calendar.get("weeks", []):
            days_list = week.get("contributionDays", [])
            if days_list:
                first_day = days_list[0].get("date")
                if first_day and first_day not in seen_weeks:
                    weekly_total = sum(d.get("contributionCount", 0) for d in days_list)
                    if first_day <= today_str or weekly_total > 0:
                        seen_weeks.add(first_day)
                        commit_trend.append({"date": first_day, "commits": weekly_total})

        return {
            "repository_growth": repo_growth,
            "star_growth": [],  # Hard to track historically without specific API
            "activity_trend": [],
            "commit_trend": commit_trend,
        }

    def _generate_recent_activity(self) -> dict[str, Any]:
        latest_commit_msg = None
        activity_file = PathManager.GENERATED_JSON_DIR / "activity.json"
        if activity_file.exists():
            activity_data = load_json(activity_file)
            if isinstance(activity_data, list):
                for event in activity_data:
                    if event.get("type") == "PushEvent":
                        commits = event.get("payload", {}).get("commits", [])
                        if commits and isinstance(commits, list):
                            latest_commit_msg = commits[-1].get("message")
                            break

        release_stats = self._calculate_release_stats()
        repo_activity = self._calculate_repo_activity()

        return {
            "latest_commit": latest_commit_msg,
            "latest_repository": repo_activity.get("recently_created_repository"),
            "latest_release": release_stats.get("latest_release"),
            "latest_update": repo_activity.get("most_recently_updated_repository"),
        }

    def _generate_profile_summary(self) -> dict[str, Any]:
        return {
            "repository_summary": f"Creator of {self._calculate_repo_stats().get('original_repository_count', 0)} repositories.",
            "language_summary": f"Primary language is {self._calculate_language_stats().get('most_used_language', 'Unknown')}.",
            "activity_summary": f"Most recently working on {self._generate_recent_activity().get('latest_update', 'Unknown')}.",
            "community_summary": f"Received {self._calculate_star_stats().get('total_stars', 0)} stars across all projects.",
        }

    def _save_output(self) -> None:
        """Save the processed statistics to a JSON file."""
        output_file = PathManager.GENERATED_STATS_DIR / "processed_statistics.json"
        save_json(self.stats, output_file)
        logger.info(f"StatisticsEngine: Saved processed statistics to {output_file}")


def process_statistics() -> dict[str, Any]:
    """Helper function to run the statistics engine."""
    engine = StatisticsEngine()
    return engine.process_all()


if __name__ == "__main__":
    from logger import setup_logger

    setup_logger()
    process_statistics()
