"""GitHub Statistics Engine for EL-STRIX."""

from datetime import UTC, datetime
from typing import Any

from logger import logger
from paths import PathManager
from utils.json_helpers import load_json, save_json


class StatisticsEngine:
    """Core engine for processing GitHub data into statistics.
    
    The Statistics Engine never communicates directly with GitHub APIs.
    It reads JSON data generated by the GitHub Data Engine and acts as the
    single source of truth for every numerical value displayed in the profile.
    """

    def __init__(self) -> None:
        """Initialize the StatisticsEngine and load raw data."""
        self.profile_data: dict[str, Any] = load_json(PathManager.GENERATED_JSON_DIR / "profile.json")
        self.repos_data: list[dict[str, Any]] = load_json(PathManager.GENERATED_JSON_DIR / "repos.json")
        if not isinstance(self.repos_data, list):
            self.repos_data = []
        self.contrib_data: dict[str, Any] = load_json(PathManager.GENERATED_JSON_DIR / "contributions.json")
        self.loc_data: dict[str, Any] = load_json(PathManager.GENERATED_JSON_DIR / "loc_stats.json")
        self.pr_data: list[dict[str, Any]] = load_json(PathManager.GENERATED_JSON_DIR / "pull_requests.json")
        if not isinstance(self.pr_data, list):
            self.pr_data = []
        self.stats: dict[str, Any] = {}

    def process_all(self) -> dict[str, Any]:
        """Execute the complete data processing pipeline."""
        logger.info("StatisticsEngine: Processing started.")
        start_time = datetime.now()

        # 1. Validation
        if not self._validate_data():
            logger.error("StatisticsEngine: Validation failed. Proceeding with available data.")

        # 2. Normalization
        self._normalize_data()

        # 3. Calculation & Aggregation
        self.stats = {
            "profile": self._calculate_profile_stats(),
            "repositories": self._calculate_repo_stats(),
            "stars": self._calculate_star_stats(),
            "forks": self._calculate_fork_stats(),
            "commits": self._calculate_commit_stats(),
            "contributions": self._calculate_contribution_stats(),
            "loc": self._calculate_loc_stats(),
            "languages": self._calculate_language_stats(),
            "activity": self._calculate_repo_activity(),
            "releases": self._calculate_release_stats(),
            "issues": self._calculate_issue_stats(),
            "pull_requests": self._calculate_pr_stats(),
            "featured_projects": self._calculate_featured_projects(),
            "trends": self._calculate_trends(),
            "recent_activity": self._generate_recent_activity(),
            "summary": self._generate_profile_summary(),
        }

        # 4. Output JSON
        self._save_output()

        duration = (datetime.now() - start_time).total_seconds()
        logger.info(f"StatisticsEngine: Processing completed in {duration:.2f}s.")
        return self.stats

    def _validate_data(self) -> bool:
        """Validate the presence and integrity of raw data."""
        valid = True
        if not self.profile_data:
            logger.warning("Validation Warning: Missing or empty profile.json")
            valid = False
        if not self.repos_data:
            logger.warning("Validation Warning: Missing or empty repos.json")
            valid = False
        if not self.contrib_data:
            logger.warning("Validation Warning: Missing or empty contributions.json")
            valid = False
        return valid

    def _normalize_data(self) -> None:
        """Normalize data structures before processing."""
        for repo in self.repos_data:
            repo["stargazers_count"] = repo.get("stargazers_count", 0)
            repo["forks_count"] = repo.get("forks_count", 0)
            repo["size"] = repo.get("size", 0)

    def _parse_date(self, date_str: str | None) -> datetime | None:
        """Parse ISO 8601 date string to datetime object."""
        if not date_str:
            return None
        try:
            return datetime.fromisoformat(date_str.replace("Z", "+00:00"))
        except ValueError:
            return None

    def _calculate_profile_stats(self) -> dict[str, Any]:
        """Calculate profile-level statistics."""
        created_at_str = self.profile_data.get("created_at")
        created_date = self._parse_date(created_at_str)
        
        days_since_creation = 0
        account_age_years = 0.0
        if created_date:
            delta = datetime.now(UTC) - created_date
            days_since_creation = delta.days
            account_age_years = round(days_since_creation / 365.25, 2)

        return {
            "total_public_repositories": self.profile_data.get("public_repos", 0),
            "total_followers": self.profile_data.get("followers", 0),
            "total_following": self.profile_data.get("following", 0),
            "profile_creation_date": created_at_str,
            "days_since_account_creation": days_since_creation,
            "account_age_years": account_age_years,
        }

    def _calculate_repo_stats(self) -> dict[str, Any]:
        """Calculate repository-level statistics."""
        public = self.profile_data.get("public_repos", sum(1 for r in self.repos_data if not r.get("private")))
        private = self.profile_data.get("total_private_repos") or sum(1 for r in self.repos_data if r.get("private"))
        total = public + private
        
        archived = sum(1 for r in self.repos_data if r.get("archived"))
        forked = sum(1 for r in self.repos_data if r.get("fork"))
        original = total - forked
        
        now = datetime.now(UTC)
        active = 0
        for r in self.repos_data:
            updated = self._parse_date(r.get("pushed_at") or r.get("updated_at"))
            if updated and (now - updated).days <= 90:
                active += 1

        return {
            "repository_count": total,
            "public_repository_count": public,
            "private_repository_count": private,
            "archived_repository_count": archived,
            "forked_repository_count": forked,
            "original_repository_count": original,
            "active_repository_count": active,
            "repository_growth": total,
        }

    def _calculate_star_stats(self) -> dict[str, Any]:
        """Calculate star-level statistics."""
        if not self.repos_data:
            return {"total_stars": 0, "average_stars": 0.0}

        stars = [r.get("stargazers_count", 0) for r in self.repos_data if not r.get("fork")]
        total = sum(stars)
        avg = round(total / len(stars), 2) if stars else 0.0
        
        repo_stars = {r.get("name", "unknown"): r.get("stargazers_count", 0) for r in self.repos_data if not r.get("fork")}
        sorted_repos = sorted(repo_stars.items(), key=lambda x: x[1], reverse=True)
        
        return {
            "total_stars": total,
            "average_stars": avg,
            "most_starred_repository": sorted_repos[0][0] if sorted_repos else None,
            "least_starred_repository": sorted_repos[-1][0] if sorted_repos else None,
            "star_ranking": [{"repository": k, "stars": v} for k, v in sorted_repos],
            "star_distribution": self._bucket_distribution(stars)
        }

    def _bucket_distribution(self, values: list[int]) -> dict[str, int]:
        """Create a generic bucketed distribution."""
        dist = {"0": 0, "1-10": 0, "11-50": 0, "51-100": 0, "100+": 0}
        for v in values:
            if v == 0:
                dist["0"] += 1
            elif v <= 10:
                dist["1-10"] += 1
            elif v <= 50:
                dist["11-50"] += 1
            elif v <= 100:
                dist["51-100"] += 1
            else:
                dist["100+"] += 1
        return dist

    def _calculate_fork_stats(self) -> dict[str, Any]:
        """Calculate fork statistics."""
        if not self.repos_data:
            return {"total_forks": 0}

        forks = [r.get("forks_count", 0) for r in self.repos_data if not r.get("fork")]
        total = sum(forks)
        avg = round(total / len(forks), 2) if forks else 0.0
        
        repo_forks = {r.get("name", "unknown"): r.get("forks_count", 0) for r in self.repos_data if not r.get("fork")}
        sorted_repos = sorted(repo_forks.items(), key=lambda x: x[1], reverse=True)
        
        return {
            "total_forks": total,
            "average_forks": avg,
            "most_forked_repository": sorted_repos[0][0] if sorted_repos else None,
            "repository_fork_rankings": [{"repository": k, "forks": v} for k, v in sorted_repos]
        }

    def _calculate_commit_stats(self) -> dict[str, Any]:
        """Calculate commit statistics."""
        public_commits = self.contrib_data.get("totalCommitContributions", 0)
        private_commits = self.contrib_data.get("restrictedContributionsCount", 0)
        return {
            "total_commits": public_commits + private_commits,
            "recent_commits": 0,
            "commit_frequency": 0.0,
            "commits_per_repository": {},
            "commit_timeline": []
        }

    def _calculate_contribution_stats(self) -> dict[str, Any]:
        """Calculate generalized contribution stats."""
        calendar = self.contrib_data.get("contributionCalendar", {})
        total = calendar.get("totalContributions", 0)
        return {
            "total_contributions": total,
            "daily_contributions": {},
            "weekly_contributions": {},
            "monthly_contributions": {},
            "yearly_contributions": total
        }

    def _calculate_loc_stats(self) -> dict[str, Any]:
        """Calculate lines of code additions and deletions."""
        additions = 0
        deletions = 0
        
        if self.loc_data and isinstance(self.loc_data, dict):
            for repo_name, data in self.loc_data.items():
                weeks = data.get("weeks", [])
                for week in weeks:
                    additions += week.get("a", 0)
                    deletions += week.get("d", 0)
                    
        return {
            "additions": additions,
            "deletions": deletions,
            "total": additions - deletions,
            "total_lines": additions + deletions
        }

    def _calculate_language_stats(self) -> dict[str, Any]:
        """Calculate language usage."""
        lang_bytes: dict[str, int] = {}
        for r in self.repos_data:
            if r.get("fork"): continue
            lang = r.get("language")
            if lang:
                lang_bytes[lang] = lang_bytes.get(lang, 0) + r.get("size", 0) * 1024

        total_bytes = sum(lang_bytes.values())
        sorted_langs = sorted(lang_bytes.items(), key=lambda x: x[1], reverse=True)
        
        percentages = {}
        if total_bytes > 0:
            percentages = {k: round((v / total_bytes) * 100, 2) for k, v in sorted_langs}

        return {
            "languages_used": len(lang_bytes),
            "total_bytes": total_bytes,
            "most_used_language": sorted_langs[0][0] if sorted_langs else None,
            "percentage_per_language": percentages,
            "language_ranking": [{"language": k, "bytes": v, "percentage": percentages.get(k)} for k, v in sorted_langs]
        }

    def _calculate_repo_activity(self) -> dict[str, Any]:
        """Calculate repository activity timing."""
        valid_repos = [r for r in self.repos_data if not r.get("fork") and r.get("created_at") and r.get("pushed_at")]
        if not valid_repos:
            return {}

        sorted_by_recent = sorted(valid_repos, key=lambda x: self._parse_date(x["pushed_at"]) or datetime.min.replace(tzinfo=UTC), reverse=True)
        sorted_by_created = sorted(valid_repos, key=lambda x: self._parse_date(x["created_at"]) or datetime.min.replace(tzinfo=UTC))
        
        return {
            "most_recently_updated_repository": sorted_by_recent[0].get("name") if sorted_by_recent else None,
            "recently_created_repository": sorted_by_created[-1].get("name") if sorted_by_created else None,
            "oldest_repository": sorted_by_created[0].get("name") if sorted_by_created else None,
            "most_active_repository": None,
            "least_active_repository": None,
        }

    def _calculate_release_stats(self) -> dict[str, Any]:
        return {
            "total_releases": 0,
            "latest_release": None,
            "release_frequency": 0.0,
            "repository_release_count": {}
        }

    def _calculate_issue_stats(self) -> dict[str, Any]:
        total = self.contrib_data.get("totalIssueContributions", 0)
        return {
            "total_issues": total,
            "open_issues": sum(r.get("open_issues_count", 0) for r in self.repos_data),
            "closed_issues": 0,
            "issue_ratio": 0.0
        }

    def _calculate_pr_stats(self) -> dict[str, Any]:
        total = len(self.pr_data)
        open_prs = sum(1 for pr in self.pr_data if pr.get("state") == "open")
        
        merged_prs = 0
        for pr in self.pr_data:
            if pr.get("merged_at"):
                merged_prs += 1
            elif pr.get("pull_request", {}).get("merged_at"):
                merged_prs += 1
                
        closed_prs = sum(1 for pr in self.pr_data if pr.get("state") == "closed") - merged_prs
        
        # If the REST API search failed or returned 0, fallback to the 1-year GraphQL total
        if total == 0:
            total = self.contrib_data.get("totalPullRequestContributions", 0)

        return {
            "total_pull_requests": total,
            "open_pull_requests": open_prs,
            "closed_pull_requests": max(0, closed_prs),
            "merged_pull_requests": merged_prs
        }

    def _calculate_featured_projects(self) -> list[dict[str, Any]]:
        """Rank repositories for featuring."""
        from projects import select_featured, format_featured
        selected = select_featured(self.repos_data, max_count=6)
        return format_featured(selected)

    def _calculate_trends(self) -> dict[str, Any]:
        return {
            "repository_growth": [],
            "star_growth": [],
            "activity_trend": [],
            "commit_trend": []
        }

    def _generate_recent_activity(self) -> dict[str, Any]:
        return {
            "latest_commit": None,
            "latest_repository": self._calculate_repo_activity().get("recently_created_repository"),
            "latest_release": None,
            "latest_update": self._calculate_repo_activity().get("most_recently_updated_repository")
        }

    def _generate_profile_summary(self) -> dict[str, Any]:
        return {
            "repository_summary": f"Creator of {self._calculate_repo_stats().get('original_repository_count', 0)} repositories.",
            "language_summary": f"Primary language is {self._calculate_language_stats().get('most_used_language', 'Unknown')}.",
            "activity_summary": f"Most recently working on {self._generate_recent_activity().get('latest_update', 'Unknown')}.",
            "community_summary": f"Received {self._calculate_star_stats().get('total_stars', 0)} stars across all projects."
        }

    def _save_output(self) -> None:
        """Save the processed statistics to a JSON file."""
        output_file = PathManager.GENERATED_STATS_DIR / "processed_statistics.json"
        save_json(self.stats, output_file)
        logger.info(f"StatisticsEngine: Saved processed statistics to {output_file}")


def process_statistics() -> dict[str, Any]:
    """Helper function to run the statistics engine."""
    engine = StatisticsEngine()
    return engine.process_all()

if __name__ == "__main__":
    from logger import setup_logger
    setup_logger()
    process_statistics()
